ds_se:
  outputs:
    dev:
      dataset: stack_exchange
      # dataset: stack_exchange_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: //home/credendials/google_cloud_credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: de-zoomcamp-ds-stackexchange
      threads: 1
      type: bigquery
  target: dev
